{{- if .Values.services.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-services
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: services
spec:
  type: {{ .Values.services.service.type }}
  ports:
    - port: {{ .Values.services.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.services.service.type "NodePort") .Values.services.service.nodePort }}
      nodePort: {{ .Values.services.service.nodePort }}
      {{- end }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: services
{{- end }}
